version: '3'
services:
  constalloca:
    build:
      context: .
    working_dir: /home/pwn
    container_name: constalloca
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9993:9999"
    entrypoint: /etc/init.sh
    restart: always
