version: '3'
services:
  noalloca:
    build:
      context: .
    working_dir: /home/pwn
    container_name: noalloca
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9991:9999"
    entrypoint: /etc/init.sh
    restart: always
