version: '3'
services:
  alloca:
    build:
      context: .
    working_dir: /home/pwn
    container_name: alloca
    ulimits:
      nproc: 65535
      core: 0
    ports:
      - "9992:9999"
    entrypoint: /etc/init.sh
    restart: always
